### ISSUE TITLE
Compatibility with `simplecov_json_formatter`

### ISSUE THREAD

**Issue by clinejj** [joshmfrankel/simplecov-check-action#8]
The `simplecov_json_formatter` [gem](https://github.com/codeclimate-community/simplecov_json_formatter) is bundled with simplecov and looks to be the recommended gem according to the documentation (see [here](https://github.com/simplecov-ruby/simplecov#json-formatter)). Any thoughts as to supporting the output of this instead of `simplecov-json` (or both)?

The main issue appears to be the `files` key isn't present in the other format, which also doesn't generate a file by file summary and this would have to be calculated instead to support the `minimum_file_coverage` configuration (see [sample](https://github.com/codeclimate-community/simplecov_json_formatter/blob/master/spec/fixtures/sample_with_branch.json))

**Comment by joshmfrankel** [comment]
That is a fair point. The reason I went with https://github.com/vicentllongo/simplecov-json was that it included several things I wanted to measure from SimpleCov's resultset. 

Specifically: 
* Covered percent (per file)
* Overall coverage percent (by suite)
* All file names covered

We could utilize the recommended gem but would have to calculated the coverage percent for every file as well as overall suite coverage. Since vicentllongo/simplecov-json provided this directly, it was a more efficient way to complete this Github action. I don't have any plans at this time to change the json gem utilized but pull requests are welcome 👍🏻
